#!/bin/bash
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get -y install ppp
cat <<'EOF' | sudo tee /etc/ppp/peers/4GLTE
#
#
hide-password 
noauth
connect "/usr/sbin/chat -v -T internet -f /etc/chatscripts/4GLTE"
debug
/dev/ttyUSB1
115200
defaultroute
noipdefault 
remotename 4GLTE
ipparam 4GLTE
usepeerdns
persist
replacedefaultroute
EOF

cat <<'EOF' | sudo tee /etc/chatscripts/4GLTE
# This chatfile was generated by pppconfig 2.3.18.
# Please do not delete any of the comments.  Pppconfig needs them.
# 
# ispauth PAP
# abortstring
ABORT BUSY ABORT 'NO CARRIER' ABORT VOICE ABORT 'NO DIALTONE' ABORT 'NO DIAL TONE' ABORT 'NO ANSWER' ABORT DELAYED
# modeminit
'' ATZ
OK-AT-OK AT+CGDCONT=1,"IP","\T","",0,0
# ispnumber
OK "ATDT*99#"
# ispconnect
CONNECT \d\c
# prelogin

# ispname
# isppassword
# postlogin

# end of pppconfig stuff
EOF
sudo chown root:dip /etc/ppp/peers/4GLTE
sudo chown root:dip /etc/chatscripts/4GLTE
sudo chmod 640 /etc/ppp/peers/4GLTE
sudo chmod 640 /etc/chatscripts/4GLTE
sudo sed -i '5i\\nallow-hotplug 4gppp0\niface 4gppp0 inet ppp\nprovider 4GLTE' /etc/network/interfaces
sudo sed -i '/sys-subsystem-net-devices/d' /lib/systemd/system/ifup@.service
sudo systemctl daemon-reload
sudo systemctl restart ifup@4gppp0
sudo systemctl enable ifup@4gppp0
cat <<'EOF' | sudo tee /etc/udev/rules.d/99-dwm222.rules
KERNEL=="ttyUSB1", ATTRS{idVendor}=="2001", ATTRS{idProduct}=="7e35", ENV{SYSTEMD_WANTS}+="ifup@4gppp0.service"
EOF
sudo udevadm control --reload
if [ -z "$1" ]
then
    curl -s 'https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg' | gpg --import && \
    if z=$(curl -s 'https://install.zerotier.com/' | gpg); then echo "$z" | sudo bash; fi
    sudo zerotier-cli join $1
fi
sudo reboot
